# Tags: 7.0-windowsservercore-ltsc2019, 7.0.100-alpha.1-windowsservercore-ltsc2019
FROM mcr.microsoft.com/dotnet/nightly/sdk:7.0-windowsservercore-ltsc2019
FROM mcr.microsoft.com/dotnet/nightly/sdk:7.0.100-alpha.1-windowsservercore-ltsc2019
