# Tags: 5.0-bullseye-slim-arm32v7, 5.0.403-bullseye-slim-arm32v7
FROM mcr.microsoft.com/dotnet/nightly/sdk:5.0-bullseye-slim-arm32v7
FROM mcr.microsoft.com/dotnet/nightly/sdk:5.0.403-bullseye-slim-arm32v7
