# Tags: 7.0-alpine3.14-amd64, 7.0.100-alpha.1-alpine3.14-amd64
FROM mcr.microsoft.com/dotnet/nightly/sdk:7.0-alpine3.14-amd64
FROM mcr.microsoft.com/dotnet/nightly/sdk:7.0.100-alpha.1-alpine3.14-amd64
