# Tags: 7.0-alpine-arm64v8, 7.0.100-alpha.1-alpine3.15-arm64v8, 7.0-alpine3.15-arm64v8
FROM mcr.microsoft.com/dotnet/nightly/sdk:7.0-alpine-arm64v8
FROM mcr.microsoft.com/dotnet/nightly/sdk:7.0.100-alpha.1-alpine3.15-arm64v8
FROM mcr.microsoft.com/dotnet/nightly/sdk:7.0-alpine3.15-arm64v8
