# Tags: 6.0-alpine-amd64, 6.0-alpine3.15-amd64, 6.0.100-alpine3.15-amd64
FROM mcr.microsoft.com/dotnet/nightly/sdk:6.0-alpine-amd64
FROM mcr.microsoft.com/dotnet/nightly/sdk:6.0-alpine3.15-amd64
FROM mcr.microsoft.com/dotnet/nightly/sdk:6.0.100-alpine3.15-amd64
