# Tags: 3.1-alpine3.15, 3.1-alpine, 3.1.415-alpine3.15
FROM mcr.microsoft.com/dotnet/nightly/sdk:3.1-alpine3.15
FROM mcr.microsoft.com/dotnet/nightly/sdk:3.1-alpine
FROM mcr.microsoft.com/dotnet/nightly/sdk:3.1.415-alpine3.15
