# Tags: 5.0-cbl-mariner1.0-amd64, 5.0.403-cbl-mariner1.0-amd64
FROM mcr.microsoft.com/dotnet/nightly/sdk:5.0-cbl-mariner1.0-amd64
FROM mcr.microsoft.com/dotnet/nightly/sdk:5.0.403-cbl-mariner1.0-amd64
