# Tags: 6.0-bullseye-slim-arm32v7, 6.0.100-bullseye-slim-arm32v7
FROM mcr.microsoft.com/dotnet/nightly/sdk:6.0-bullseye-slim-arm32v7
FROM mcr.microsoft.com/dotnet/nightly/sdk:6.0.100-bullseye-slim-arm32v7
