# Tags: 6.0-windowsservercore-ltsc2022, 6.0.100-windowsservercore-ltsc2022
FROM mcr.microsoft.com/dotnet/nightly/sdk:6.0-windowsservercore-ltsc2022
FROM mcr.microsoft.com/dotnet/nightly/sdk:6.0.100-windowsservercore-ltsc2022
