# Tags: 7.0-windowsservercore-ltsc2022, 7.0.100-alpha.1-windowsservercore-ltsc2022
FROM mcr.microsoft.com/dotnet/nightly/sdk:7.0-windowsservercore-ltsc2022
FROM mcr.microsoft.com/dotnet/nightly/sdk:7.0.100-alpha.1-windowsservercore-ltsc2022
