# Tags: 5.0-windowsservercore-ltsc2019, 5.0.403-windowsservercore-ltsc2019
FROM mcr.microsoft.com/dotnet/nightly/sdk:5.0-windowsservercore-ltsc2019
FROM mcr.microsoft.com/dotnet/nightly/sdk:5.0.403-windowsservercore-ltsc2019
