# Tags: 5.0-alpine-amd64, 5.0-alpine3.15-amd64, 5.0.403-alpine3.15-amd64
FROM mcr.microsoft.com/dotnet/nightly/sdk:5.0-alpine-amd64
FROM mcr.microsoft.com/dotnet/nightly/sdk:5.0-alpine3.15-amd64
FROM mcr.microsoft.com/dotnet/nightly/sdk:5.0.403-alpine3.15-amd64
