# Tags: 6.0-bullseye-slim-arm64v8, 6.0.100-bullseye-slim-arm64v8
FROM mcr.microsoft.com/dotnet/nightly/sdk:6.0-bullseye-slim-arm64v8
FROM mcr.microsoft.com/dotnet/nightly/sdk:6.0.100-bullseye-slim-arm64v8
