# Tags: 6.0-cbl-mariner1.0-amd64, 6.0.100-cbl-mariner1.0-amd64
FROM mcr.microsoft.com/dotnet/nightly/sdk:6.0-cbl-mariner1.0-amd64
FROM mcr.microsoft.com/dotnet/nightly/sdk:6.0.100-cbl-mariner1.0-amd64
