# Tags: 5.0-nanoserver-2009, 5.0-nanoserver-20H2, 5.0.403-nanoserver-2009, 5.0.403-nanoserver-20H2
FROM mcr.microsoft.com/dotnet/nightly/sdk:5.0-nanoserver-2009
FROM mcr.microsoft.com/dotnet/nightly/sdk:5.0-nanoserver-20H2
FROM mcr.microsoft.com/dotnet/nightly/sdk:5.0.403-nanoserver-2009
FROM mcr.microsoft.com/dotnet/nightly/sdk:5.0.403-nanoserver-20H2
