# Tags: 5.0-windowsservercore-ltsc2022, 5.0.403-windowsservercore-ltsc2022
FROM mcr.microsoft.com/dotnet/nightly/sdk:5.0-windowsservercore-ltsc2022
FROM mcr.microsoft.com/dotnet/nightly/sdk:5.0.403-windowsservercore-ltsc2022
