# Tags: 6.0-windowsservercore-ltsc2019, 6.0.100-windowsservercore-ltsc2019
FROM mcr.microsoft.com/dotnet/nightly/sdk:6.0-windowsservercore-ltsc2019
FROM mcr.microsoft.com/dotnet/nightly/sdk:6.0.100-windowsservercore-ltsc2019
